backend:
  name: github
  repo: trietng/trietng.github.io
  branch: main
  base_url: https://cms-auth.trietnguyen0781.workers.dev
media_folder: public/images
public_folder: /images
slug:
  encoding: ascii
  clean_accents: true
i18n:
  structure: multiple_folders
  locales: [en, vi]
  default_locale: en
collections:
  - label: Pages
    name: pages
    i18n: true
    files:
      - label: Home
        name: home
        file: src/pages/{{locale}}/index.md
        i18n: true
        format: markdown
        fields:
          - { label: Layout, name: layout, widget: hidden, default: ../../layouts/IndexLayout.astro, i18n: duplicate }
          - label: Title
            name: title
            widget: object
            i18n: duplicate
            fields:
              - { label: Greeting, name: greeting, widget: string, i18n: true }
              - { label: Name, name: name, widget: string, i18n: true }
          - { label: Summary, name: summary, widget: string, i18n: true }
          - { label: Welcome, name: welcome, widget: markdown, i18n: true }
          - label: Education
            name: education
            widget: object
            i18n: duplicate
            fields:
              - { label: School, name: school, widget: string, i18n: true }
              - { label: Degree, name: degree, widget: string, i18n: true }
              - { label: Major, name: major, widget: string, i18n: true }
              - { label: Description, name: description, widget: markdown, i18n: true }
              - { label: Graduation date, name: graduationDate, widget: datetime, time_format: false, i18n: duplicate }
          - label: Translations
            name: translations
            widget: object
            i18n: duplicate
            fields:
              - { label: expectedGraduationDate, name: expectedGraduationDate, widget: string, i18n: true }
              - { label: education, name: education, widget: string, i18n: true }
              - { label: workExperience, name: workExperience, widget: string, i18n: true }
              - { label: skills, name: skills, widget: string, i18n: true }
              - { label: projects, name: projects, widget: string, i18n: true }
              - { label: contactMe, name: contactMe, widget: string, i18n: true }
              - { label: present, name: present, widget: string, i18n: true }
              - { label: primarySkills, name: primarySkills, widget: string, i18n: true }
              - { label: secondarySkills, name: secondarySkills, widget: string, i18n: true }
              - { label: primarySkillsDescription, name: primarySkillsDescription, widget: string, i18n: true }
              - { label: secondarySkillsDescription, name: secondarySkillsDescription, widget: string, i18n: true }
  - label: Skills
    name: skills
    i18n: true
    icon: star
    files:
      - label: Skills
        name: skills
        file: src/content/skills/skills.md
        fields:
          - label: Skills
            name: skills
            widget: list
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Description, name: body, widget: markdown, required: false }
              - { label: Icon, name: icon, widget: image }
              - label: Type
                name: type
                widget: select
                options:
                  - { label: Language, value: language }
                  - { label: Framework, value: framework }
                  - { label: Library, value: library }
                  - { label: Tool, value: tool }
                  - { label: Database, value: database }
                default: language
              - label: Level
                name: level
                widget: select
                options:
                  - { label: Beginner, value: beginner }
                  - { label: Intermediate, value: intermediate }
                  - { label: Advanced, value: advanced }
                default: beginner
              - label: Tier
                name: tier
                widget: select
                options:
                  - { label: Primary, value: primary }
                  - { label: Secondary, value: secondary }
                default: secondary
  - label: Work experience
    name: work-experience
    folder: src/content/work-experience
    icon: work
    slug: '{{company}}-{{title}}-{{startDate}}'
    summary: '{{company}} - {{title}}'
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Company, name: company, widget: string }
      - { label: Start date, name: startDate, widget: datetime, time_format: false }
      - { label: End date, name: endDate, widget: datetime, time_format: false, required: false }
      - { label: Location, name: location, widget: string }
      - { label: Description, name: body, widget: markdown }
  - label: Projects
    name: projects
    folder: src/content/projects
    slug: '{{name}}'
    summary: '{{name}}'
    icon: done_outline
    create: true
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Description, name: body, widget: markdown }
      - label: Priority
        name: priority
        widget: select
        options:
          - { label: Low, value: low }
          - { label: Medium, value: medium }
          - { label: High, value: high }
        default: medium
      - { label: Repository, name: repository, widget: list, required: false }
      - { label: Demo, name: demo, widget: string, required: false }
      - { label: Featured, name: featured, widget: boolean, default: true, required: false }