backend:
  name: github
  repo: trietng/trietng.github.io
  branch: main
  base_url: https://cms-auth.trietnguyen0781.workers.dev
media_folder: public/images
public_folder: /images
slug:
  encoding: ascii
  clean_accents: true
collections:
  - label: Khóa học
    name: course
    folder: src/pages/course
    create: true
    identifier_field: name
    fields:
      - {label: Layout, name: layout, widget: hidden, default: ../../layouts/CourseLayout.astro}