backend:
  name: github
  repo: trietng/trietng.github.io
  branch: main
  base_url: https://cms-auth.trietnguyen0781.workers.dev
media_folder: public/images
public_folder: /images
slug:
  encoding: ascii
  clean_accents: true
i18n:
  structure: multiple_folders
  locales: [en, vi]
  default_locale: en
collections:
  - label: Pages
    name: pages
    i18n: true
    files:
      - label: Home
        name: home
        file: src/pages/{{locale}}/index.md
        create: false
        i18n: true
        fields:
          - { label: Layout, name: layout, widget: hidden, default: ../../layouts/IndexLayout.astro, i18n: duplicate }
          - label: Title
            name: title
            widget: object
            i18n: duplicate
            fields:
              - { label: Greeting, name: greeting, widget: string, i18n: true }
              - { label: Name, name: name, widget: string, i18n: true }
          - { label: Summary, name: summary, widget: string, i18n: true }